name: Roguelite
version: 1.1
main: com.monumenta.roguelite.Main
description: test
api-version: 1.16
depend: [MonumentaStructureManagement]

commands:
  roguelite:
    usage: /roguelite <args...>
    description: for all roguelite things ;p
    permission: monumenta.roguelite
