name: Roguelite
version: 1.1
main: com.monumenta.rl2.Main
description: test
api-version: 1.16

commands:
  roguelite:
    usage: /roguelite <args...>
    description: for all roguelite things ;p
    permission: bukkit.command.give
